[target.armv7-unknown-linux-gnueabihf.env]
volumes = [
    "BUILD_DIR",
]
[target.x86_64-unknown-linux-musl]
pre-build = ["apt-get update && apt-get install --assume-yes libtss2-dev llvm-dev libclang-dev clang libc6-dev"]
